package views;

import javax.swing.JFrame;

import javax.swing.JButton;
import views.Form;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import java.awt.Color;

/**
 *
 * @author manda
 */
public class Homepage extends javax.swing.JFrame {
    private JButton[] moodButtons;
    private String username;
    public Homepage(String username) {
        this.username = username;
        initComponents();
        moodButtons = new JButton[]{bmalu, bhappy, bsulking, bflushed, blovely, bkaget};
        welcome.setText("Hi, "+username);
        setVisible(true);
        setTitle("Homepage");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }
    
    private void clearMoodSelection() {
        for (JButton btn : moodButtons) {
            btn.setBorder(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String mood = "";
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bmalu = new javax.swing.JButton();
        bsulking = new javax.swing.JButton();
        bhappy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bflushed = new javax.swing.JButton();
        blovely = new javax.swing.JButton();
        bkaget = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        history = new javax.swing.JButton();
        addMood = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 600));

        welcome.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 102, 102));
        welcome.setText("Hi, Amanda");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("How's Your Day ?");

        bmalu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/TikTok Embarrassed Emoji PNG-Photoroom.png"))); // NOI18N
        bmalu.setBorder(null);
        bmalu.setContentAreaFilled(false);
        bmalu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bmalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmaluActionPerformed(evt);
            }
        });

        bsulking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/TikTok Sulk Emoji PNG-Photoroom.png"))); // NOI18N
        bsulking.setBorder(null);
        bsulking.setContentAreaFilled(false);
        bsulking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsulking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsulkingMouseClicked(evt);
            }
        });
        bsulking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsulkingActionPerformed(evt);
            }
        });

        bhappy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/TikTok Happy Emoji PNG-Photoroom.png"))); // NOI18N
        bhappy.setBorder(null);
        bhappy.setContentAreaFilled(false);
        bhappy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhappyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Sulking");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Happy");

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Embarrassed");

        bflushed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/TikTok Flushed Emoji PNG-Photoroom.png"))); // NOI18N
        bflushed.setBorder(null);
        bflushed.setContentAreaFilled(false);
        bflushed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bflushed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bflushedActionPerformed(evt);
            }
        });

        blovely.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/TikTok Lovely Emoji PNG-Photoroom.png"))); // NOI18N
        blovely.setBorder(null);
        blovely.setContentAreaFilled(false);
        blovely.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blovely.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blovelyActionPerformed(evt);
            }
        });

        bkaget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emoji/TikTok Surprised Emoji PNG-Photoroom.png"))); // NOI18N
        bkaget.setBorder(null);
        bkaget.setContentAreaFilled(false);
        bkaget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkaget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkagetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Flushed");

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Lovely");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Surprised");

        history.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        history.setForeground(new java.awt.Color(51, 102, 255));
        history.setText("History");
        history.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        history.setContentAreaFilled(false);
        history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        addMood.setBackground(new java.awt.Color(51, 102, 255));
        addMood.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        addMood.setForeground(new java.awt.Color(255, 255, 255));
        addMood.setText("Add My Mood");
        addMood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        addMood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bflushed, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(blovely, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(21, 21, 21))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bsulking, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel3)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(bhappy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(21, 21, 21)))))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bmalu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bkaget, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel8))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addMood, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(129, 129, 129))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(welcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bmalu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsulking, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhappy, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bkaget, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bflushed, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blovely, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMood, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmaluActionPerformed
        clearMoodSelection();
        bmalu.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
        mood = "EMBARRASSED 👉👈";
    }//GEN-LAST:event_bmaluActionPerformed

    private void bsulkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsulkingActionPerformed
        clearMoodSelection();
        bsulking.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
        mood = "SULKING 😤";
    }//GEN-LAST:event_bsulkingActionPerformed

    private void bhappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhappyActionPerformed
        clearMoodSelection();
        bhappy.setBorder(BorderFactory.createLineBorder(Color.PINK, 3));
        mood = "HAPPY 😚";
    }//GEN-LAST:event_bhappyActionPerformed

    private void bflushedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bflushedActionPerformed
        clearMoodSelection();
        bflushed.setBorder(BorderFactory.createLineBorder(Color.YELLOW, 3));
        mood = "FLUSHED 😳";
    }//GEN-LAST:event_bflushedActionPerformed

    private void blovelyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blovelyActionPerformed
        clearMoodSelection();
        blovely.setBorder(BorderFactory.createLineBorder(Color.PINK, 3));
        mood = "LOVELY 😍";
    }//GEN-LAST:event_blovelyActionPerformed

    private void bkagetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkagetActionPerformed
        clearMoodSelection();
        bkaget.setBorder(BorderFactory.createLineBorder(Color.PINK, 3));
        mood = "SURPRISED 😱";
    }//GEN-LAST:event_bkagetActionPerformed

    private void addMoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoodActionPerformed
        if(!mood.isEmpty()){
            new Form(this).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Tentukan mood mu hari ini.");
        }
    }//GEN-LAST:event_addMoodActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        new History(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_historyActionPerformed

    private void bsulkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsulkingMouseClicked
       
    }//GEN-LAST:event_bsulkingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Homepage(username).setVisible(true);
//            }
//        });
    }
    
    public String getMood(){
        return mood;
    }
    public String getUsername(){
        return username;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMood;
    private javax.swing.JButton bflushed;
    private javax.swing.JButton bhappy;
    private javax.swing.JButton bkaget;
    private javax.swing.JButton blovely;
    private javax.swing.JButton bmalu;
    private javax.swing.JButton bsulking;
    private javax.swing.JButton history;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
